import Head from 'next/head'
import React from 'react'

function About() {
    return (
        <div className="container">
            <Head>
                <title>About</title>
                <meta name="description" content="Generated by create next app" />  
            </Head>
        </div>
    )
}

export default About
