import { gql, useMutation } from "@apollo/client";
import Head from "next/head";
import React, { useState } from "react";
import Button from "react-bootstrap/Button";
import Form from "../components/Form";
import GoHome from "../components/GoHome";
import TextInput from "../components/TextInput";
import styles from "../styles/Form.module.css";
import classes from "../styles/Home.module.css";
function Create() {
  const [name, setName] = useState("");
  const [age, setAge] = useState("");
  const [title, setTitle] = useState("");
  const [image, setImage] = useState("");

  const createImage = (e) => {
    setImage(e.target.files[0]);
    console.log(setImage);
  };

  const createName = (e) => {
    setName(e.target.value);
  };

  const createAge = (e) => {
    setAge(e.target.value);
  };

  const createTitle = (e) => {
    setTitle(e.target.value);
  };

  const [createUser] = useMutation(gql`
    mutation Mutation($createUserInput: CreateUserInput!) {
      createUser(createUserInput: $createUserInput) {
        _id
        image
        name
        title
        age
      }
    }
  `);

  const addUser = (e) => {
    e.preventDefault();
    createUser({
      variables: {
        createUserInput: {
          image,
          name,
          age: Number(age),
          title,
        },
      },
    });
    alert("User successfully added");
  };
  return (
    <>
      <main className={styles.main}>
        <div className={classes.container}>
          <Head>
            <title>Create a user </title>
            <meta name="description" content="Generated by create next app" />
          </Head>

          <div className="column">
            <Form>
              <h1>Create a User</h1>
              <p>Profile Picture</p>
              <TextInput
                type="file"
                placeholder="choose an image"
                onChange={createImage}
                icon=" "
                required
              />

              <p>Name</p>
              <TextInput
                type="text"
                placeholder="Enter Name"
                onChange={createName}
                value={name}
                icon=" "
                required
              />

              <p>Age</p>
              <TextInput
                type="number"
                placeholder="Enter age"
                onChange={createAge}
                value={age}
                icon=" "
                required
              />

              <p>Title</p>
              <TextInput
                type="text"
                placeholder="Enter title"
                onChange={createTitle}
                value={title}
                icon=" "
                required
              />

              <Button
                className="action__btn m-2"
                variant="primary"
                onClick={addUser}
              >
                Create
              </Button>
              <GoHome />
            </Form>
          </div>
        </div>
      </main>
    </>
  );
}

export default Create;
